version: '3'

services:
  mysql:
    container_name: cryptocompare-mysql
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data/:/var/lib/mysql
    #  - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    cap_add:
      - sys_nice #SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cryptocompare
      MYSQL_USER: user_cryptocompare
      MYSQL_PASSWORD: password_cryptocompare
    ports:
      - "127.0.0.1:3307:3306"
    networks:
      - cryptocompare

  cryptocompare:
    container_name: cryptocompare
    image: github.com/vench/cryptocompare:local
    restart: always
    ports:
      - "8081:8081"
    networks:
      - cryptocompare
    environment:
      MYSQL_CONNECTION_STRING: 'user_cryptocompare:password_cryptocompare@tcp(mysql:3306)/cryptocompare'
    depends_on:
      - mysql

networks:
  cryptocompare:
    driver: bridge
